version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - PORT=8080
    # O comando extra garante que funcione bem no chip M da Apple
    platform: linux/arm64

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    platform: linux/arm64